#!/bin/bash
FILE=.settings
if [ ! -f "$FILE" ]; then
touch .settings
echo "Enter IP address of server: "
read IPADD
echo "Enter Username: "
read USERNAME
echo "Enter Remote Directory to Watch (Default ~/watch): "
read WATCHDIR
echo "Enter Custom SSH Key Name (Default id_rsa): "
read KEYNAME
echo -e "IPADD=$IPADD\nUSERNAME=$USERNAME\nWATCHDIR=\"$WATCHDIR\"\nKEYNAME=$KEYNAME" >> .settings
ssh -i ~/.ssh/$KEYNAME $USERNAME@$IPADD "touch $WATCHDIR/.lastcheck"
else
source $FILE
fi

for f in $(ssh -i ~/.ssh/$KEYNAME $USERNAME@$IPADD "find $WATCHDIR -type f -newercm $WATCHDIR/.lastcheck")
do
scp -i ~/.ssh/$KEYNAME $USERNAME@$IPADD:$f ./
done
ssh -i ~/.ssh/$KEYNAME $USERNAME@$IPADD "touch $WATCHDIR/.lastcheck"