#!/bin/bash
FILE=.settings
if [ ! -f "$FILE" ]
then
touch .settings
echo "Enter IP address of server: "
read IPADD
echo "Enter Username: "
read USERNAME
echo "Enter Password: "
read PASSWORD
echo -e "IPADD=$IPADD\nUSERNAME=$USERNAME\nPASSWORD=$PASSWORD" >> .settings
else
source $FILE
fi