/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;



class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    // I am unsure on how to test these files but I think Alex said do not worry about test for this assignment... I think
