/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.List;
import java.util.Scanner;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(readMe("src/main/resources/gates.js"));

    }

    public static String readMe(String gatesPath) {
        String errorsFound = new String();
        int count = 0;

        try {
            Scanner scanner = new Scanner(new File(gatesPath));
            int lineCount = 0;
            while(scanner.hasNextLine()) {
                lineCount++;
                String next = scanner.nextLine();
                //from w3 did I use this correctly?
                if(!(next.isEmpty() || next.endsWith("{") || next.endsWith("}") || next.contains("if")
                        || next.contains("else")) && !next.endsWith(";")) {
                    errorsFound.join("Line " + lineCount + ": Missing Semicolon.");
                    count++;
                }
            }
        } catch (Exception error) {
            error.printStackTrace();
        }
        System.out.println("Number of errors: " + count);
        return errorsFound.toString();

    }

}